<a href="https://colab.research.google.com/github/CamelGoong/PY_TensorFlow/blob/main/Part02_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 02 텐서플로2 주요 특징


In [1]:
import tensorflow as tf
print(tf.executing_eagerly())

True


In [3]:
a = 1
b = 2
c = tf.math.add(a, b)
print(c)
c.numpy()

tf.Tensor(3, shape=(), dtype=int32)


3

#03 텐서플로 자료구조



> 3-1 스칼라(Scalar)



In [7]:
a = tf.constant(1)
b = tf.constant(2)

print("a: ", a)
print("b: ", b)

print("a의 차수 확인: ", tf.rank(a))


a:  tf.Tensor(1, shape=(), dtype=int32)
b:  tf.Tensor(2, shape=(), dtype=int32)
a의 차수 확인:  tf.Tensor(0, shape=(), dtype=int32)


In [8]:
# 텐서의 자료형 변환
a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)
print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'float32'>


In [12]:
c = tf.math.add(a,b)
print(c)
print(c.dtype)

tf.Tensor(3.0, shape=(), dtype=float32)
<dtype: 'float32'>




> 3-2 벡터



In [13]:
import tensorflow as tf
import numpy as np

# 1차원 배열 정의
py_list = [10., 20., 30.]
num_array = np.array([10., 20., 30.])

# 텐서 변환
vec1 = tf.constant(py_list, dtype = tf.float32)
vec2 = tf.constant(num_array, dtype = tf.float32)

print(vec1)
print(vec2)

tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)


In [15]:
# 덧셈
add1 = tf.math.add(vec1, vec2)
print("result: ", add1)

# 거듭제곱
square1 = tf.math.square(vec1)
print("result: ", square1)

result:  tf.Tensor([20. 40. 60.], shape=(3,), dtype=float32)
result:  tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)




> 3-3 행렬(Matrix)



In [16]:
import tensorflow as tf
list_of_list = [[10, 20], [30, 40]]

mat1 = tf.constant(list_of_list)
print("rank: ", tf.rank(mat1))
print("mat1", mat1)

rank:  tf.Tensor(2, shape=(), dtype=int32)
mat1 tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [17]:
# stack 함수를 이용해서 행렬 만들기
vec1 = tf.constant([1,0])
vec2 = tf.constant([-1, 2])

# 텐서 변환
mat2 = tf.stack([vec1, vec2])

print("mat2: ", mat2)

mat2:  tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


In [18]:
# element by element 연산(multiply는 그냥 같은 위치에 있는 원소끼리의 곱셈)
element_mul = tf.math.multiply(mat1, mat2)
print("result: ", element_mul)

result:  tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)


In [19]:
# 행렬곱(matmul)
mat_mul = tf.matmul(mat1, mat2)
print("result: ", mat_mul)

result:  tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)


In [20]:
# 텐서를 넘파이로 변환
np_arr = mat_mul.numpy()
print(np_arr)
print(type(np_arr))

[[-10  40]
 [-10  80]]
<class 'numpy.ndarray'>


> 3-4 고차원 텐서

In [21]:
# 3차원 텐서
import tensorflow as tf
import numpy as np

# 2차원 배열 정의
mat1 = [[1, 2, 3, 4],
        [5, 6, 7, 8]]
mat2 = [[9, 10, 11, 12],
        [13, 14, 15, 16]]
mat3 = [[17, 18, 19, 20],
        [21, 22, 23, 24]]

# 텐서 변환
tensor1 = tf.constant([mat1, mat2, mat3])

print("rank: ", tf.rank(tensor1))
print("result: ", tensor1)

rank:  tf.Tensor(3, shape=(), dtype=int32)
result:  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [23]:
# 4차원 텐서
tensor2 = tensor1

tensor4 = tf.stack([tensor1, tensor2])
print("rank: ", tf.rank(tensor4))
print("result: ", tensor4)

rank:  tf.Tensor(4, shape=(), dtype=int32)
result:  tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]], shape=(2, 3, 2, 4), dtype=int32)


> 04 인덱싱(indexing)

In [26]:
# 2차원 텐서 인덱싱
mat = tf.constant([[10, 20, 30],
                  [40, 50, 60]])
print(mat[0,0])

tf.Tensor(10, shape=(), dtype=int32)


In [28]:
# 3차원 텐서 인덱싱
tensor = tf.constant([
                      [[10, 20, 30],
                       [40, 50 ,60]],
                      [[-10, -20, -30],
                       [-40, -50, -60]]
])

print(tensor)

print(tensor[0, :, :])

tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


> 05 형태 변환(tf.reshape)

In [1]:
import tensorflow as tf
tensor = tf.constant(range(0, 24))
print(tensor)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [10]:
# 1차원 벡터 -> 2차원 벡터 / 처음 1차원 벡터의 원소의 갯수가 24개였으므로, 이 원소의 갯수를 유지하는 한, 어떤 형태의 행렬로도 형태의 변환이 가능
tensor1 = tf.reshape(tensor, (3, -1))
print(tensor1)

tensor2 = tf.reshape(tensor, (-1, 4))
print(tensor2)

# 2차원 벡터 -> 1차원 벡터
tensor3 = tf.reshape(tensor2, (-1))
print(tensor3)

# 1차원 벡터 -> 3차원 벡터
tensor4 = tf.reshape(tensor3, (-1, 3, 4))
print(tensor4)

# 3차원 텐서 -> 4차원 텐서
tensor5 = tf.reshape(tensor4, (3, 2, 2, 2))
print(tensor5)

tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]], shape=(3, 2, 2, 2), dtype=int32)


> 변수(tf.variable)

In [11]:
import tensorflow as tf

tensor1 = tf.constant([[0, 1, 2],
                       [3, 4, 5]])

tensor_var1 = tf.Variable(tensor1)

print(tensor1)
print(tensor_var1)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>


In [13]:
# assign 메소드로 variable에 새로운 배열 할당
tensor_var1.assign([[1, 1, 1],
                    [2, 2, 3]])
print(tensor_var1)

# 변수 -> 텐서로 변환. / convert_to_tensor()
tensor2 = tf.convert_to_tensor(tensor_var1)
print(tensor2)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 3]], dtype=int32)>
tf.Tensor(
[[1 1 1]
 [2 2 3]], shape=(2, 3), dtype=int32)


> 자동 미분(Automatic Differentiation)

In [15]:
import tensorflow as tf

# y = 3x - 2의 선형관계를 갖는 데이터셋 생성
g = tf.random.Generator.from_seed(2020)
x = g.normal(shape = (10,)) # 10개의 1차원 벡터 생성.
y = 3 * x - 2

print("x: ", x.numpy())
print("y: ", y.numpy())

x:  [-0.20943771  1.2746525   1.213214   -0.17576954  1.876984    0.16379917
  1.082245    0.6199966  -0.4440221   1.3048344 ]
y:  [-2.628313    1.8239574   1.6396422  -2.5273085   3.630952   -1.5086025
  1.2467351  -0.14001012 -3.3320663   1.9145031 ]


In [16]:
# Loss 손실함수 정의
def cal_mse(x, y, a, b):

  y_pred = a * x + b
  squared_error = (y_pred - y) ** 2
  mean_squared_error = tf.reduce_mean(squared_error)

  return mean_squared_error

In [17]:
# tf.GradientTape로 자동 미분 과정을 기록

# 변수 생성
a = tf.Variable(0.0) # 계수
b = tf.Variable(0.0) # 상수항

EPOCHS = 200

for epoch in range(1, EPOCHS + 1):

  with tf.GradientTape() as tape:
    mse = cal_mse(x, y, a, b)

    grad = tape.gradient(mse, {"a": a, "b": b})
    d_a, d_b = grad["a"], grad["b"]

# 학습율을 곱해서 Gradient descent 사용.
    a.assign_sub(d_a * 0.05)
    b.assign_sub(d_b * 0.05)
    
    if epoch % 20 == 0: # 20 epochs마다 미분값 출력.
      print("EPOCH %d - MSE: %.4f ----- a: %.2f ----- b: %.2f"%(epoch, mse, a, b))

EPOCH 20 - MSE: 1.1415 ----- a: 1.74 ----- b: -0.75
EPOCH 40 - MSE: 0.2881 ----- a: 2.37 ----- b: -1.37
EPOCH 60 - MSE: 0.0728 ----- a: 2.69 ----- b: -1.68
EPOCH 80 - MSE: 0.0184 ----- a: 2.84 ----- b: -1.84
EPOCH 100 - MSE: 0.0046 ----- a: 2.92 ----- b: -1.92
EPOCH 120 - MSE: 0.0012 ----- a: 2.96 ----- b: -1.96
EPOCH 140 - MSE: 0.0003 ----- a: 2.98 ----- b: -1.98
EPOCH 160 - MSE: 0.0001 ----- a: 2.99 ----- b: -1.99
EPOCH 180 - MSE: 0.0000 ----- a: 2.99 ----- b: -1.99
EPOCH 200 - MSE: 0.0000 ----- a: 3.00 ----- b: -2.00
